[project]
protostar-version = "0.9.3"
lib-path = "lib"
linked-libraries = ["src/main1","src/deposit"]

[contracts]
main1 = ["src/main1"]
main2 = ["src/main2"]
open = ["src/open"]
deposit = ["src/deposit"]


